# Generated by Django 4.0.3 on 2024-04-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_pais_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='telefono',
        ),
    ]
