# Generated by Django 4.0.3 on 2024-04-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_item_porcentaje_ganancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemunidadmedida',
            name='equivalencia',
        ),
    ]
