# Generated by Django 4.0.3 on 2024-04-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_itemunidadmedida_equivalencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemunidadmedidastock',
            name='stockcomprometido',
        ),
    ]
