# Generated by Django 4.0.3 on 2024-04-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_itemunidadmedidastock_stockcomprometido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaventa',
            name='sesioncaja',
        ),
    ]
