# Generated by Django 4.0.3 on 2024-04-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_sesioncaja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaventa',
            name='valordescuento',
        ),
        migrations.RemoveField(
            model_name='facturaventa',
            name='valorflete',
        ),
        migrations.RemoveField(
            model_name='facturaventadetalle',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='facturaventadetalle',
            name='descuento_aplicado',
        ),
    ]
